# Generated by Django 2.2.5 on 2019-10-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.IntegerField(default=0)),
                ('num_gafas', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VR.Aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VR.Curso')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gafas',
            new_name='Gafa',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
